name: Feature request
description: Request a new feature.
labels: [ "feature" ]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a proper title and description to the issue.
        
        **Note: Before submitting a feature request, please check the existing issues to ensure that
        your request has not been previously suggested.**
        
        **By submitting this issue, you agree to follow the project's
        [code of conduct](https://github.com/JackEblan/Geto/blob/master/CODE_OF_CONDUCT.md).**
        
        **Please check and verify that you are using the latest version of Geto before
        submitting this bug report.**
        
        **Your feature request will be reviewed, and its implementation will be considered based on
        project goals and priorities.**
        
        **All issues must be reported in English. Issues in other languages may be closed
        without further consideration**

  - type: checkboxes
    id: checklist
    attributes:
      label: Issue Checklist
      options:
        - label: I confirm that this feature request has not been previously suggested.
          required: true
        - label: I agree to follow the project's code of conduct.
          required: true
        - label: I have checked and verified that I am using the latest version of Geto from GitHub or F-Droid.
          required: true
  - type: checkboxes
    id: additional-terms
    attributes:
      label: Additional terms
      options:
        - label: I understand that feature requests are subject to evaluation and may not be implemented immediately.
          required: true
        - label: I agree to provide additional details if needed for a clearer understanding of the requested feature.
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      placeholder: Please provide a detailed description of the feature you are requesting.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      placeholder: Explain the use case or scenario where this feature would be beneficial.
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      placeholder: Describe the benefits or improvements this feature would bring to Geto.
    validations:
      required: true